#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

RELEASE=debug
RELEASE_FLAG=

RELEASE=release
RELEASE_FLAG=--release

#TARGET=armv7-unknown-linux-gnueabihf # Pi 2/3/4
TARGET=armv7-unknown-linux-musleabihf # Pi 2/3/4
PI_NAME=slate

RUSTFLAGS="-C linker=arm-linux-gnueabihf-gcc" \
         cargo build --no-default-features --features=spi ${RELEASE_FLAG} --target $TARGET

# upload binary
scp -S ssh-ident -r ./target/$TARGET/${RELEASE}/slate assets.toml Rocket.toml ${PI_NAME}:/home/crzysdrs/

# execute binary
ssh -t ${PI_NAME} 'sudo RUST_BACKTRACE=1 ./slate'
